### ISSUE TITLE
Is it possible to include a handle to a public telegram group for my pool?

### ISSUE THREAD

**Issue by den-is** [SinglePoolAlliance/Registration#691]
Well, the title says everything.
Interested if it is possible to direct people to my public group instead of giving my handle directly.
public group handle - name part of a custom invitation link to my group. `https://t.me/[custom_group_handle]`. Similar to how it is included in my extended metadata json.

**Comment by leo42** [comment]
You can add it in the social media section, but the telegram handle of the operator needs to be  a personal handle. This is for verifying your identity in Telegram
