### ISSUE TITLE
Will it break anything adding more social media acocunts?

### ISSUE THREAD

**Issue by ccgarant** [SinglePoolAlliance/Registration#728]
Can we add more social media accounts to the JSON registration file? Will that break anything? Example, adding **Matrix**, a decentralized communication protocol, like Signal meets Discord:

> {
>  "ticker": " ",                                                      											 # Mandatory
>  "poolId": " ", 		                           # Mandatory
>  "social": {                                                          										    	  # At least 1 Mandatory more optional
>    "twitter": " ",
>    "facebook": " ",  
>    "instagram": " ",
>    "youtube": " ",
>    "matrix": "****can we add more social accounts?*****" 
>  },
>  "telegram": "????",                                             					# Mandatory Personal Telegram Handle
>  "operatorName": " ",                                					   # Optional
>  "github": ""                                                     						# Optional
> }	
> 

Ref: [matrix.org](https://matrix.org/)

**Comment by leo42** [comment]
No feel free to as as many as you like
